export {default as HeroPage} from "./Hero"
export {default as NavPage} from "./Nav"
export {default as NavMobilePage} from "./NavMobile"
export {default as AboutPage} from "./AboutMe"
export { default as ProjectPage } from "./Projects"
